version: '3.7'
services:
  web:
    env_file:
      - ./docker/production/.env/.env
    build:
      context: .
      dockerfile: ./docker/production/web/Dockerfile
    ports:
      - 8001:8000
    volumes:
      - ./web/:/usr/src/web/
    entrypoint: /entrypoint.sh
    restart: always
    depends_on:
      - database
  database:
    image: postgres:12.0-alpine
    hostname: postgres
    volumes:
      - database:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
  nginx:
    env_file:
      - ./docker/production/.env/.env
    ports:
      - 80:80
    build:
      context: .
      dockerfile: ./docker/production/nginx/Dockerfile
volumes:
  database:
