# Generated by Django 3.1.1 on 2020-11-27 15:47

import dictionary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='photo',
            field=models.ImageField(default='theme/default.jpg', upload_to=dictionary.models.upload_theme_path),
        ),
    ]
