# Generated by Django 3.1.1 on 2020-12-03 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_theme_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WordTheme',
        ),
    ]
